# Generated by Django 4.1.7 on 2023-06-17 07:21

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="StateCodes",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("state_name", models.CharField(max_length=100)),
                ("state_code", models.IntegerField(max_length=50)),
                ("status", models.BooleanField(default=True)),
            ],
        ),
    ]
