# Generated by Django 4.1.7 on 2023-06-17 07:23

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="statecodes",
            name="state_name",
            field=models.CharField(max_length=90),
        ),
    ]
