# Generated by Django 4.1.7 on 2023-06-16 12:42

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("bills", "0002_alter_bill_account_type_account_type_name"),
    ]

    operations = [
        migrations.AlterField(
            model_name="bill_banks",
            name="open_balance",
            field=models.CharField(max_length=10),
        ),
    ]
