# Generated by Django 4.1.7 on 2023-06-17 12:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0002_alter_statecodes_state_name"),
        ("bills", "0003_alter_bill_banks_open_balance"),
    ]

    operations = [
        migrations.AddField(
            model_name="bill_banks",
            name="StateCode",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                to="api.statecodes",
                verbose_name="State Code",
            ),
            preserve_default=False,
        ),
    ]
