# Generated by Django 4.1.7 on 2023-07-21 09:32

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("bills", "0005_alter_bill_banks_gstnumber"),
    ]

    operations = [
        migrations.AlterField(
            model_name="bill_banks",
            name="gstNumber",
            field=models.CharField(max_length=15),
        ),
    ]
