# Generated by Django 4.1.7 on 2023-07-21 09:43

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("bills", "0006_alter_bill_banks_gstnumber"),
    ]

    operations = [
        migrations.AlterField(
            model_name="bill_banks",
            name="created_at",
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
