# Generated by Django 4.1.7 on 2023-07-27 15:22

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("bills", "0007_alter_bill_banks_created_at"),
    ]

    operations = [
        migrations.CreateModel(
            name="Bill_Cash",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "cash_name",
                    models.CharField(max_length=100, verbose_name="Cash_name"),
                ),
                (
                    "cash_balance",
                    models.IntegerField(max_length=10, verbose_name="Cash Balance"),
                ),
                ("add_date", models.DateTimeField(auto_now_add=True)),
                ("modify_date", models.DateTimeField(auto_now=True)),
                (
                    "user_id",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
