# Generated by Django 4.1.7 on 2023-08-09 15:51

import api.bills.models
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("api", "0005_rename_customer_register_dealer_customer_bool"),
        ("bills", "0009_alter_bill_banks_primary_type_places_group_category"),
    ]

    operations = [
        migrations.CreateModel(
            name="Customer",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("cust_name", models.CharField(blank=True, max_length=150)),
                ("cust_code", models.CharField(default=0, max_length=10)),
                (
                    "image",
                    models.ImageField(
                        default="customer/profile_default.jpg",
                        upload_to=api.bills.models.upload_to,
                        verbose_name="Image",
                    ),
                ),
                ("cust_pincode", models.IntegerField(max_length=5)),
                ("cust_mobile", models.CharField(max_length=12)),
                ("cust_landline", models.CharField(max_length=12)),
                ("cust_email", models.CharField(blank=True, max_length=150)),
                ("address", models.CharField(max_length=50)),
                ("cust_is_reg", models.BooleanField(default=True)),
                ("cust_gst", models.CharField(max_length=15)),
                ("export_option", models.BooleanField(default=True)),
                ("created_by", models.CharField(max_length=10)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("modified_by", models.CharField(max_length=10)),
                ("modified_date", models.DateTimeField(auto_now=True)),
                ("status", models.BooleanField(default=True)),
                (
                    "cust_currency",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="api.currency",
                        verbose_name="State Code",
                    ),
                ),
                (
                    "cust_dealer_type",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="api.register_dealer",
                        verbose_name="State Code",
                    ),
                ),
                (
                    "cust_group",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="bills.group"
                    ),
                ),
                (
                    "cust_place",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="bills.places"
                    ),
                ),
                (
                    "cust_state_id",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="api.statecodes",
                        verbose_name="State Code",
                    ),
                ),
                (
                    "export_type",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="api.export",
                        verbose_name="State Code",
                    ),
                ),
                (
                    "master_id",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
