# Generated by Django 4.1.7 on 2023-08-09 16:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0005_rename_customer_register_dealer_customer_bool"),
        ("bills", "0010_customer"),
    ]

    operations = [
        migrations.RenameField(
            model_name="customer",
            old_name="image",
            new_name="Image",
        ),
        migrations.AlterField(
            model_name="customer",
            name="cust_currency",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="api.currency",
                verbose_name="Currency",
            ),
        ),
        migrations.AlterField(
            model_name="customer",
            name="cust_dealer_type",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="api.register_dealer",
                verbose_name="Register Dealer Type",
            ),
        ),
        migrations.AlterField(
            model_name="customer",
            name="export_type",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="api.export",
                verbose_name="Export type",
            ),
        ),
    ]
