# Generated by Django 4.1.7 on 2023-08-10 15:28

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("bills", "0012_alter_customer_cust_pincode"),
    ]

    operations = [
        migrations.AddField(
            model_name="customer",
            name="cust_pan",
            field=models.CharField(default=1212121212, max_length=10),
            preserve_default=False,
        ),
    ]
