# Generated by Django 4.1.7 on 2023-08-10 15:30

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("bills", "0013_customer_cust_pan"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="customer",
            name="cust_pan",
        ),
    ]
