# Generated by Django 4.1.7 on 2023-08-11 08:37

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("bills", "0015_customer_cust_pan"),
    ]

    operations = [
        migrations.CreateModel(
            name="CustomerLimit",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("is_limit", models.BooleanField(default=True)),
                ("amount", models.IntegerField(default=0, max_length=10)),
                ("cust_openingBalance", models.IntegerField(default=0, max_length=10)),
                ("sales_type", models.CharField(max_length=15)),
                ("rcm", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "cust_id",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="bills.customer"
                    ),
                ),
                (
                    "user_id",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
