# Generated by Django 4.1.7 on 2023-08-13 06:47

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("bills", "0016_customerlimit"),
    ]

    operations = [
        migrations.RenameField(
            model_name="customerlimit",
            old_name="is_limit",
            new_name="is_limit_cond",
        ),
    ]
