# Generated by Django 4.1.7 on 2023-08-22 10:57

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("bills", "0017_rename_is_limit_customerlimit_is_limit_cond"),
    ]

    operations = [
        migrations.CreateModel(
            name="Bill_messages",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("message", models.CharField(max_length=500, verbose_name="Message")),
                (
                    "ShortId",
                    models.CharField(max_length=100, verbose_name="Unique Identifier"),
                ),
                ("timestamp", models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
