# Generated by Django 4.1.7 on 2023-09-16 19:59

import api.bills.models
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("api", "0005_rename_customer_register_dealer_customer_bool"),
        ("bills", "0018_bill_messages"),
    ]

    operations = [
        migrations.CreateModel(
            name="Bill_invoce",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "is_logo_img",
                    models.BooleanField(max_length=500, verbose_name="Print Option"),
                ),
                (
                    "logo",
                    models.ImageField(
                        default="invoice/inv_logo.jpg",
                        upload_to=api.bills.models.upload_to_invoice,
                        verbose_name="Image",
                    ),
                ),
                ("logo_text", models.CharField(max_length=3, verbose_name="Logo Text")),
                (
                    "term_condition",
                    models.CharField(max_length=500, verbose_name="T&C"),
                ),
                (
                    "additional_option_type",
                    models.BooleanField(verbose_name="Add_Options"),
                ),
                (
                    "option_values",
                    models.CharField(max_length=50, verbose_name="option Values"),
                ),
                (
                    "ecommerce_trader",
                    models.BooleanField(verbose_name="ecommerce_trader"),
                ),
                ("reverse_charge", models.BooleanField(verbose_name="reverse_charge")),
                (
                    "to_bill_ship_applicable",
                    models.BooleanField(verbose_name="bill_ship_applicable"),
                ),
                (
                    "gst_shipping_address",
                    models.BooleanField(verbose_name="gst_shipping_address"),
                ),
                (
                    "from_date",
                    models.CharField(max_length=100, verbose_name="from Date"),
                ),
                ("till_date", models.CharField(max_length=100, verbose_name="to Date")),
                ("date_time", models.DateTimeField(auto_now_add=True)),
                (
                    "currency",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="api.currency",
                        verbose_name="Currency",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="InvoiceTemplate",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "temp_name",
                    models.CharField(max_length=50, verbose_name="Template Name"),
                ),
                (
                    "temp_path",
                    models.CharField(max_length=50, verbose_name="Template Path"),
                ),
                ("date_time", models.DateTimeField(auto_now_add=True)),
                ("status", models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name="Bill_Series",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("series_num", models.IntegerField(verbose_name="Series Num")),
                ("name", models.CharField(max_length=50, verbose_name="Name")),
                (
                    "prefix_surfix_type",
                    models.BooleanField(default=True, verbose_name="Prefix_Sufix"),
                ),
                ("sl_num", models.CharField(max_length=10, verbose_name="serial num")),
                ("prefix_surfix", models.CharField(max_length=6, verbose_name="Ufix")),
                ("primary_type", models.BooleanField(verbose_name="Primary Type")),
                (
                    "genrate_invoice",
                    models.BooleanField(default=False, verbose_name="Generate Invoice"),
                ),
                ("date_time", models.DateTimeField(auto_now_add=True)),
                (
                    "invoice_id",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="bills.bill_invoce",
                    ),
                ),
                (
                    "user_id",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="bill_invoce",
            name="invoice_design_temp",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="bills.invoicetemplate",
                verbose_name="Invoice Template",
            ),
        ),
        migrations.AddField(
            model_name="bill_invoce",
            name="user_id",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL
            ),
        ),
    ]
