# Generated by Django 4.1.7 on 2023-09-17 13:02

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("bills", "0019_bill_invoce_invoicetemplate_bill_series_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="bill_banks",
            name="gstNumber",
            field=models.CharField(max_length=15, null=True),
        ),
    ]
