# Generated by Django 4.1.7 on 2023-11-24 11:59

import api.bills.models
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("bills", "0022_alter_bill_invoce_bank_def_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="bill_invoce",
            name="logo",
            field=models.ImageField(
                default="invoice/inv_logo.jpg",
                null=True,
                upload_to=api.bills.models.upload_to_invoice,
                verbose_name="Image",
            ),
        ),
        migrations.AlterField(
            model_name="bill_series",
            name="prefix_surfix",
            field=models.CharField(max_length=6, verbose_name="PSfix"),
        ),
    ]
