# Generated by Django 4.1.7 on 2023-03-07 11:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("user", "0002_alter_roles_id"),
    ]

    operations = [
        migrations.RenameField(model_name="roles", old_name="id", new_name="role_id",),
        migrations.AlterField(
            model_name="newuser",
            name="role_id",
            field=models.ForeignKey(
                db_column="role_id",
                on_delete=django.db.models.deletion.CASCADE,
                to="user.roles",
            ),
        ),
    ]
