# Generated by Django 4.1.7 on 2023-03-07 11:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("user", "0003_rename_id_roles_role_id_alter_newuser_role_id"),
    ]

    operations = [
        migrations.RemoveField(model_name="newuser", name="joining_date",),
        migrations.RemoveField(model_name="newuser", name="updated_at",),
    ]
