# Generated by Django 4.1.7 on 2023-03-07 11:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("user", "0004_remove_newuser_joining_date_and_more"),
    ]

    operations = [
        migrations.RemoveField(model_name="newuser", name="last_ip",),
    ]
