# Generated by Django 4.1.7 on 2023-03-07 11:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("user", "0006_newuser_joining_date_newuser_last_ip_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="newuser",
            name="role_id",
            field=models.IntegerField(default=0, max_length=1, verbose_name="Role Id"),
        ),
    ]
