# Generated by Django 4.1.7 on 2023-03-07 11:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("user", "0007_alter_newuser_role_id"),
    ]

    operations = [
        migrations.AlterField(
            model_name="roles",
            name="role_name",
            field=models.CharField(
                choices=[
                    ("SUPERUSER", "Superuser"),
                    ("OWNER", "Owner"),
                    ("DISTRIBUTOR", "Distributor"),
                    ("SALES", "Sales"),
                    ("HEAD_OFFICE", "Head Office"),
                    ("CUSTOMER", "Customer"),
                    ("USER", "User"),
                ],
                max_length=50,
            ),
        ),
    ]
