# Generated by Django 4.1.7 on 2023-03-07 13:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("user", "0009_delete_roles_alter_newuser_role_id"),
    ]

    operations = [
        migrations.AlterField(
            model_name="newuser",
            name="role_id",
            field=models.CharField(
                choices=[
                    ("1", "Superuser"),
                    ("2", "Owner"),
                    ("3", "Distributor"),
                    ("4", "Sales"),
                    ("5", "Head Office"),
                    ("6", "Customer"),
                    ("7", "User"),
                ],
                max_length=50,
            ),
        ),
    ]
