# Generated by Django 4.1.7 on 2023-03-07 13:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("user", "0010_alter_newuser_role_id"),
    ]

    operations = [
        migrations.AddField(
            model_name="newuser",
            name="sess_token",
            field=models.CharField(default=0, max_length=10),
        ),
    ]
