# Generated by Django 4.1.7 on 2023-03-17 18:09

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("user", "0011_newuser_sess_token"),
    ]

    operations = [
        migrations.CreateModel(
            name="Bill_manage_info",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("reason", models.CharField(max_length=100)),
                ("cin_number", models.CharField(max_length=100)),
                ("sms_credit", models.IntegerField(max_length=1000)),
                ("sms_debit", models.IntegerField(max_length=1000)),
                ("system_credit", models.IntegerField(max_length=1000)),
                ("system_debit", models.IntegerField(max_length=1000)),
                ("whatsapp_credit", models.IntegerField(max_length=1000)),
                ("whatsapp_debit", models.IntegerField(max_length=1000)),
                ("shortname", models.CharField(max_length=50)),
                ("pan_card", models.CharField(max_length=16)),
                ("is_regdealer", models.BooleanField(verbose_name="Is regular Dealer")),
                ("stateCode", models.IntegerField(max_length=3)),
                ("gstNum", models.CharField(max_length=14)),
                ("reg_dealer_type", models.IntegerField()),
                ("pin_code", models.IntegerField(max_length=5)),
                ("status_type", models.IntegerField(max_length=2)),
                ("kyc", models.CharField(max_length=50)),
                ("landlineNUM", models.IntegerField(max_length=8)),
                ("actual_billQty", models.BooleanField(verbose_name="Bill Quantity")),
                ("edit_status", models.BooleanField(verbose_name="edit status")),
                ("last_updated", models.DateTimeField(auto_now=True)),
                (
                    "user_id",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="",
                    ),
                ),
            ],
        ),
    ]
