# Generated by Django 4.1.7 on 2023-04-04 08:29

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("user", "0013_alter_bill_manage_info_landlinenum_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="bill_manage_info",
            name="landlineNUM",
            field=models.CharField(max_length=12),
        ),
    ]
