# Generated by Django 4.1.7 on 2023-04-12 16:10

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("user", "0014_alter_bill_manage_info_landlinenum"),
    ]

    operations = [
        migrations.AddField(
            model_name="newuser",
            name="owner_id",
            field=models.IntegerField(default=0, max_length=3, verbose_name="Owner ID"),
        ),
    ]
