# Generated by Django 4.1.7 on 2023-04-17 07:46

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("user", "0015_newuser_owner_id"),
    ]

    operations = [
        migrations.AlterField(
            model_name="newuser",
            name="is_active",
            field=models.BooleanField(default=True),
        ),
    ]
