# Generated by Django 4.1.7 on 2023-06-17 12:53

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0002_alter_statecodes_state_name"),
        ("user", "0016_alter_newuser_is_active"),
    ]

    operations = [
        migrations.AlterField(
            model_name="bill_manage_info",
            name="stateCode",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="api.statecodes",
                verbose_name="State Code",
            ),
        ),
        migrations.AlterField(
            model_name="bill_manage_info",
            name="user_id",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to=settings.AUTH_USER_MODEL,
                verbose_name="User",
            ),
        ),
    ]
