# Generated by Django 4.1.7 on 2023-08-09 14:54

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("user", "0017_alter_bill_manage_info_statecode_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="newuser",
            name="role_id",
            field=models.CharField(
                choices=[
                    ("1", "Superuser"),
                    ("2", "Owner"),
                    ("3", "Distributor"),
                    ("4", "Sales"),
                    ("5", "Head Office"),
                    ("6", "Branch"),
                    ("7", "Customer"),
                ],
                max_length=50,
            ),
        ),
    ]
